#' random.sdtm.data Package
#'
#' Create Random SDTM Datasets
#'
#' @description
#' A set of functions to create random Study Data Tabulation Model (SDTM)
#' datasets. SDTM dataset specifications are described by the Clinical Data
#' Interchange Standards Consortium (CDISC) SDTM Implementation Guide.
#'
#' @details
#' The random SDTM datasets generated by this package include:
#' \itemize{
#'   \item DM - Demographics
#'   \item SUPPDM - Supplementory Demographics
#'   \item AE - Adverse Events
#'   \item SUPPAE - Supplementory Adverse Events
#'   \item CM - Concomitant Medications
#'   \item EX - Exposure
#'   \item LB - Laboratory Test Results
#'   \item VS - Vital Signs
#'   \item DS - Disposition
#'   \item MH - Medical History
#'   \item SV - Subject Visits
#'   \item EG - ECG Test Results
#' }
#'
#' @docType package
#' @name random.sdtm.data
#' @import checkmate
#' @import dplyr
#' @importFrom lifecycle deprecated
#' @importFrom lubridate ymd days weeks
#' @importFrom magrittr %>%
#' @importFrom purrr map map2 pmap
#' @importFrom rlang .data
#' @importFrom stats rnorm runif rbinom rpois
#' @importFrom tibble tibble
#' @importFrom tidyr unnest
#' @importFrom utils data
"_PACKAGE"
