
# reg Function to create synthetic EG dataset
reg <- function(domain = "EG",
                testcd = c(),
                test = c(),
                unit_org = c(),
                unit_std = c(),
                drop_vars = c()) {

  # Metadata for the EG dataset
  eg_metadata <- list("STUDYID" = "Study Identifier",
                      "DOMAIN" = "Domain Abbreviation",
                      "USUBJID" = "Unique Subject Identifier",
                      "SPDEVID" = "Sponsor Device Identifier",
                      "EGSEQ" = "Sequence Number",
                      "EGGRPID" = "Group ID",
                      "EGREFID" = "ECG Reference ID",
                      "EGSPID" = "Sponsor-Defined Identifier",
                      "EGBEATNO" = "ECG Beat Number",
                      "EGTESTCD" = "ECG Test or Examination Short Name",
                      "EGTEST" = "ECG Test or Examination Name",
                      "EGCAT" = "Category for ECG",
                      "EGSCAT" = "Subcategory for ECG",
                      "EGPOS" = "ECG Position of Subject",
                      "EGORRES" = "Result or Finding in Original Units",
                      "EGORRESU" = "Original Units",
                      "EGSTRESC" = "Character Result/Finding in Std Format",
                      "EGSTRESN" = "Numeric Result/Finding in Standard Units",
                      "EGSTRESU" = "Standard Units",
                      "EGSTAT" = "Completion Status",
                      "EGREASND" = "Reason ECG Not Done",
                      "EGXFN" = "ECG External File Path",
                      "EGNAM" = "Vendor Name",
                      "EGMETHOD" = "Method of Test or Examination",
                      "EGLEAD" = "Lead Location Used for Measurement",
                      "EGLOBXFL" = "Last Observation Before Exposure Flag",
                      "EGBLFL" = "Baseline Flag",
                      "EGDRVFL" = "Derived Flag",
                      "EGEVAL" = "Evaluator",
                      "EGEVALID" = "Evaluator Identifier",
                      "EGCLSIG" = "Clinically Significant, Collected",
                      "EGREPNUM" = "Repetition Number",
                      "VISITNUM" = "Visit Number",
                      "VISIT" = "Visit Name",
                      "VISITDY" = "Planned Study Day of Visit",
                      "TAETORD" = "Planned Order of Element within Arm",
                      "EPOCH" = "Epoch",
                      "EGDTC" = "Date/Time of ECG",
                      "EGDY" = "Study Day of ECG",
                      "EGTPT" = "Planned Time Point Name",
                      "EGTPTNUM" = "Planned Time Point Number",
                      "EGELTM" = "Planned Elapsed Time from Time Point Ref",
                      "EGTPTREF" = "Time Point Reference",
                      "EGRFTDTC" = "Date/Time of Reference Time Point")
  
  
}