# R/suppdm.R
#' Create SUPPDM Dataset with BMI Category
#'
#' @description
#' Generates a supplemental SDTM SUPPDM dataset containing the derived BMI category (BMI_CAT)
#' based on randomly generated height and weight.
#'
#' @param dm A data.frame representing the DM dataset, ideally generated by `rdm()`
#' @param height_range Numeric vector of length 2, min and max height in cm (default: c(150, 190))
#' @param weight_range Numeric vector of length 2, min and max weight in kg (default: c(50, 120))
#' @param seed Optional integer for reproducibility
#'
#' @return A data.frame with SDTM SUPPDM structure containing BMI_CAT
#' @export
#'
#' @examples
#' suppdm <- r_suppdm(dm)


r_suppdm <- function(dm,
                     height_range = c(150, 190),
                     weight_range = c(50, 120),
                     seed = NULL) {
  assert_data_frame(dm)
  assert_numeric(height_range, len = 2)
  assert_numeric(weight_range, len = 2)
  assert_number(seed, null.ok = TRUE)

  if (!is.null(seed)) set.seed(seed)

  dm_bmi <- dm %>%
    mutate(
      HEIGHT_CM = runif(n(), min = height_range[1], max = height_range[2]),
      WEIGHT_KG = runif(n(), min = weight_range[1], max = weight_range[2]),
      BMI = round(WEIGHT_KG / (HEIGHT_CM / 100)^2, 1),
      BMI_CAT = as.character(cut(
        BMI,
        breaks = c(-Inf, 18.5, 24.9, 29.9, Inf),
        labels = c("NORMAL", "OVERWEIGHT", "OBESE")
      ))
    )

  suppdm <- dm_bmi %>%
    select(STUDYID, USUBJID, SUBJID, BMI_CAT) %>%
    mutate(
      QNAM = "BMI_CAT",
      QLABEL = "BMI Category (WHO)",
      QVAL = BMI_CAT,
      RDOMAIN = "DM",
      IDVAR = "",
      IDVARVAL = NA_real_,
      QORIG = "DERIVED",
      QEVAL = "SYSTEM"
    ) %>%
    select(STUDYID, RDOMAIN, USUBJID, IDVAR, IDVARVAL, QNAM, QLABEL, QVAL, QORIG, QEVAL)

  suppdm <- apply_metadata(suppdm, list(
    STUDYID   = "Study Identifier",
    RDOMAIN   = "Related Domain Abbreviation",
    USUBJID   = "Unique Subject Identifier",
    IDVAR     = "Identifying Variable",
    IDVARVAL  = "Identifying Variable Value",
    QNAM      = "Qualifier Variable Name",
    QLABEL    = "Qualifier Variable Label",
    QVAL      = "Data Value",
    QORIG     = "Origin",
    QEVAL     = "Evaluator"
  ))

  return(suppdm)
}

suppdm <- r_suppdm(dm)

