library(dplyr)
library(tidyr)
library(purrr)
library(checkmate)
library(rlang)
library(tibble)
library(lubridate)
library(stringr)

# Global requirement
studyid <- "AD2025"
set.seed(2025)

apply_metadata <- function(data, metadata) {
  checkmate::assert_data_frame(data)
  checkmate::assert_list(metadata)

  for (var in names(metadata)) {
    if (var %in% names(data)) {
      attr(data[[var]], "label") <- metadata[[var]]
    }
  }

  data
}

# Function to check if optional variable has required input or else creating dummy values
opt_var_chk <- function(opt_var, comp_var){

  # Getting values of the provided parameters for comparison
  opt_val <- get(opt_var, envir = parent.frame())
  comp_val <- get(comp_var, envir = parent.frame())

  # If Optional parameter included, then No. of Optional parameter's value and Comparator value should be matched
  if (length(opt_val) > 0 & length(opt_val) != length(comp_val)) {
    stop(paste0("Error: No. of ", toupper(opt_var), " and ", toupper(comp_var), " provided not matched. Add NA values if any of the ", toupper(comp_var), " doesn't require ",toupper(opt_var)))
  }

  # Creation of dummy value for Optional parameter, if it is not included
  if (length(opt_val) == 0) {
    opt_var <- c(rep(NA, length(comp_val)))
  } else {
    opt_var <- opt_val
  }

  return(opt_var)
}

# Function to create random values within specific range, specific decimal with specified probability of NA values
rand_res <- function(n, mean, sd, min, max, dec, na_prob = 0.1) {

  set.seed(1122)  # for reproducibility

  if (na_prob > 1 | na_prob < 0) {
    stop("Error: Input for na_prob should between 0 to 1.")
  }
  # Generate normal values
  values <- rnorm(n, mean = mean, sd = sd)

  # Clip values to a specific range
  if (length(min) > 0 | length(max) > 0) {
    values <- pmin(pmax(values, min), max)
  }

  # Round to decimal places
  if (length(dec) > 0) {
    values <- round(values, dec)
  }

  # Introduce missing values randomly
  missing_indices <- sample(1:n, size = round(na_prob * n))  # 10% missing
  values[missing_indices] <- NA

  return(values)
}

# Function to map Sequence variable
seqnum <- function(df, sort = c()) {

  var_name <- paste0(unique(df$DOMAIN), "SEQ")

  temp1 <- df %>%
    arrange(!!!parse_exprs(sort)) %>%
    group_by(USUBJID) %>%
    mutate(!!sym(var_name) := row_number()) %>%
    ungroup()

  return(temp1)
}

# Function to map Epoch variable
epoch <- function(df, dtc) {

  # Merging with SE
  temp1 <- merge(df, se, by = "USUBJID")

  # Getting latest EPOCH value for each date within each Subject
  temp2 <- temp1 %>%
    filter(SESTDTC <= !!sym(dtc) & !!sym(dtc) <= SEENDTC) %>%
    arrange(USUBJID, !!sym(dtc), -TAETORD) %>%
    group_by(USUBJID, !!sym(dtc)) %>%
    filter(row_number() == 1)

  # Joining the EPOCH to the input dataframe
  temp3 <- left_join(df, temp2 %>% select(USUBJID, !!sym(dtc), EPOCH), by = c("USUBJID", dtc))

  return(temp3)
}

# Function to map Study Day variables
stdy <- function(df, dtc) {

  # Creating --DY variable name
  dy_var <- gsub("DTC", "DY", dtc)

  # Joining RFSTDTC frpm DM and calculating --DY Values
  temp1 <- left_join(df, dm %>% select(USUBJID, RFSTDTC), by = c("USUBJID")) %>%
    mutate(!!sym(dy_var) := ifelse(!is.na(!!sym(dtc)) & length(!!sym(dtc)) > 0 & !is.na(RFSTDTC) & length(RFSTDTC) > 0,
                                   ifelse(!!sym(dtc) >= RFSTDTC, as.integer((as.Date(!!sym(dtc)) - as.Date(RFSTDTC))  + 1), as.integer(as.Date(!!sym(dtc)) - as.Date(RFSTDTC))),
                                   NA_integer_))

  return(temp1)
}

# Function to map LOBXFL variable
lobxfl <- function(df, dtc, res_var, sort = c()){

  # VLOBXFL variable name based on DOMAIN
  var_name <- paste0(unique(df$DOMAIN), "LOBXFL")

  # Removing dtc column from sort list and adding it at last to sort in descending order
  grp_var <- c(na.omit(gsub(dtc, NA, sort)))
  sort_in <- c(grp_var, c(paste0("-",dtc)))

  # Filtering only non-missing result values & records before Exposure date, Based on sort group assigning "Y" for the LOBXFL variable
  temp1 <- df %>%
    left_join(., dm %>%  select(USUBJID, RFXSTDTC), by = c("USUBJID")) %>%
    filter(!!sym(res_var) != "" | !is.na(!!sym(res_var))) %>%
    filter(!!sym(dtc) < RFXSTDTC) %>%
    arrange(!!!(sort_in)) %>%
    group_by(!!!syms(grp_var)) %>%
    filter(row_number() == n()) %>%
    mutate(!!sym(var_name) := "Y") %>%
    ungroup()

  # Joining the LOBXFL variable to the input dataframe based on the group variables
  temp2 <- left_join(df, temp1 %>% select(all_of(grp_var), !!sym(dtc), !!sym(var_name)), by = c(grp_var, dtc))

  return(temp2)
}


# Dummy SV creation

sv1 <- crossing(dm %>% select(USUBJID, RFSTDTC), tv) %>%
  mutate(SVOCCUR = "Y",
         SVSTDTC = RFSTDTC) %>%
  filter(row_number() %in% c(1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13,
                             21, 22, 23, 24, 25, 26, 27,
                             31,
                             41, 42,
                             51, 52, 53,
                             61, 62, 63, 64, 65, 66,
                             71, 72, 73, 75, 79,
                             84, 85, 86,
                             92, 94, 96, 98, 99))

unsch <- data.frame(USUBJID = c("AD2025-00005", "AD2025-00005", "AD2025-00005", "AD2025-00007", "AD2025-00007", "AD2025-00008", "AD2025-00010"),
                    VISIT = c("Unscheduled", "Unscheduled", "Unscheduled", "Unscheduled", "Unscheduled", "Unscheduled", "Unscheduled"),
                    VISITNUM = c(99, 99, 99, 99, 99, 99, 99),
                    SVOCCUR = c("N", "Y", "Y", "N", "Y", "N", "Y"),
                    SVSTDTC = as.Date(c("2026-02-02", "2025-02-12", "2026-12-02", "2026-09-02", "2023-10-02", "2026-02-22", "2022-02-02")))


sv <- bind_rows(sv1, unsch) %>%  select(USUBJID, VISIT, VISITNUM, SVOCCUR, SVSTDTC) %>% arrange(USUBJID, VISITNUM, SVSTDTC)

# Dummy SE creation
se1 <- crossing(dm, te %>%  select(-DOMAIN, -STUDYID))

se <- se1 %>%
  mutate(SESTDTC = case_when(ELEMENT == "Screening" ~ RFICDTC,
                             ELEMENT == "Treatment" ~ RFXSTDTC,
                             ELEMENT == "Follow-up" ~ RFENDTC),
         SEENDTC = case_when(ELEMENT == "Screening" ~ RFXSTDTC,
                             ELEMENT == "Treatment" ~ RFXENDTC,
                             ELEMENT == "Follow-up" ~ RFENDTC),
         EPOCH =   case_when(ELEMENT == "Screening" ~ "SCREENING",
                             ELEMENT == "Treatment" ~ "TRT",
                             ELEMENT == "Follow-up" ~ "FUP"),
         TAETORD = case_when(ELEMENT == "Screening" ~ 1,
                             ELEMENT == "Treatment" ~ 2,
                             ELEMENT == "Follow-up" ~ 3))

# Checks for dates of subjects that die during study
death_dates <- ae %>%
  dplyr::filter(AEOUT == "DEATH") %>%
  dplyr::group_by(USUBJID) %>%
  dplyr::summarise(death_date = min(AESTDTC)) # Use min in case of multiple death records

# List of ae terms
ae_terms <- tibble::tibble(
  AETERM   = c(
    "RIGHT OTITIS"                 ,
    "RAID (COATED) IN THE MOUTH"                 ,
    "NON CARDIAC CHEST PAIN"                 ,
    "DIABETES MELLITUS"                 ,
    "UPPER RESPIRATORY TRACT INFECTION"                 ,
    "BRUISE ON THE RIGHT LOWER LEG"                 ,
    "ORAL THRUSH"                 ,
    "WORSENING PSORIATIC ARTHRITIS"                 ,
    "NASAL CONGESTION"                 ,
    "TREMORS OF LEGS"                 ,
    "REACTION AT THE INJECTION SITE (RIGHT THIGH)"                 ,
    "DIARRHOEA"                 ,
    "STOMATITIS"                 ,
    "COMMON COLD"                 ,
    "BAKER'S PSEUDOCYST ON THE RIGHT"                 ,
    "WORSENING HYPOKALEMIA"                 ,
    "BRUISING AT DOSING CANNULA SITE (LEFT ARM)"                 ,
    "SEIZURE SYMPTOM(ARMS EXTEND)"                 ,
    "HERPES ON THE LIPS"                 ,
    "PHARYNGITIS"                 ,
    "INCREASED AST- EXERCISE-INDUCED LAB ABNORMALITY"                 ,
    "MUCOSITIS ORAL"                 ,
    "NAUSEA"                 ,
    "NAUSEA"                 ,
    "DEAFNESS NEUROSENSORY"                 ,
    "EPITAXIS"                 ,
    "FEVER"                 ,
    "INFECTION (INCREASED WBC)"                 ,
    "CONTACT DERMATITIS LEFT ANTICUBITAL FOSSA (SECONDARY TO CANNULA DRESSING)"                 ,
    "TACHYCARDIA"                 ,
    "PAIN(RIGHT FLANK)"                 ,
    "COMMON COLD"                 ,
    "VAGINAL YEAST INFECTION ACCORDING VIPSUAL INSPECTION"                 ,
    "HYPERGLYCEMIA"                 ,
    "IRRITABILITY"                 ,
    "BRUISE ON ABDOMEN"                 ,
    "INCREASED BLOOD PRESSIRE"                 ,
    "INCREASED CK - EXERCISE-INDUCED LABORATORY ABNORMALITY"                 ,
    "AXILIARY AND INGUINAL-GLUTEAL LESIONS HS FLARE"                 ,
    "ESCPHAGEAL CANDIDIASIS"                 ,
    "MUSCULOSKELETAL PAIN"                 ,
    "URTICARIAL IMP INJECTION SITE REACTION BILATERAL THIGHS"                 ,
    "ANXIETY"                 ,
    "INTERVERTEBRAL DISC HERNIATION"                 ,
    "INFLUENZA VIRAL INFECTION"                 ,
    "STOMATITIS"                 ,
    "ERYTHRASMA"                 ,
    "HEADACHE"                 ,
    "INCREASED LDH-EXERCISE-INDUCED LAB ABNORMALITY"                 ,
    "BLOOD IN URINE"                 ,
    "INCREASED CK-EXERCISE-INDUCED LAB ABNORMALITY"                 ,
    "INFECTIO TRACTUS URINARY"                 ,
    "PAIN AT LEFT KNEE"                 ,
    "CHOLELITHIASIS"                 ,
    "LIPOMAS OF BACK"                 ,
    "FEVER"                 ,
    "LOWER BACK ACHE"                 ,
    "LOWER BACK PAIN"                 ,
    "HS EXACERBATION"                 ,
    "HEADACHE"                 ,
    "MODERATE PAIN IN THE ARM CORRELATED TO COVID-19 VACCINE (PFIZER - COMIRNATY)"                 ,
    "VAGINAL YEAST INFECTION"                 ,
    "INFLUENZALIKE SYMPTOMS"                 ,
    "DYSHIDROSIC ECZEMA OF BOTH HANDS"                 ,
    "LEFT SIDE RIB FRACTURE"                 ,
    "SCALP PSORIASIS"                 ,
    "FRACTURE OF RIGHT SPHENOIDALE (FOOT)"                 ,
    "FOLLICULITIS ON ABDOMEN (LOCALIZED, SUPERFICIAL)"                 ,
    "NAUSEA"                 ,
    "CONTACT DERMAITIS (AXILLAE)"                 ,
    "INJECTION SITE REACTION"                 ,
    "ATOPIC DERMATITIS LESION (RIGHT EYELID)"                 ,
    "CONJUNCTIRITIS"                 ,
    "UPPER RESPIRATORY TRACT INFECTION"                 ,
    "RIGHT ANTI-CUBITAL FOSSA CONTACT  DERMATITIS (SECONDARY TO CANNULA DRESSING)"),
  AEDECOD  = c(
    "Ear infection"                 ,
    "Coating in mouth"                 ,
    "Non-cardiac chest pain"                 ,
    "Diabetes mellitus"                 ,
    "Upper respiratory tract infection"                 ,
    "Contusion"                 ,
    "Oral candidiasis"                 ,
    "Psoriatic arthropathy"                 ,
    "Nasal congestion"                 ,
    "Tremor"                 ,
    "Injection site reaction"                 ,
    "Diarrhoea"                 ,
    "Stomatitis"                 ,
    "Nasopharyngitis"                 ,
    "Synovial cyst"                 ,
    "Hypokalaemia"                 ,
    "Catheter site bruise"                 ,
    "Seizure"                 ,
    "Oral herpes"                 ,
    "Pharyngitis"                 ,
    "Aspartate aminotransferase increased"                 ,
    "Stomatitis"                 ,
    "Nausea"                 ,
    "Nausea"                 ,
    "Deafness neurosensory"                 ,
    "Epistaxis"                 ,
    "Pyrexia"                 ,
    "Infection"                 ,
    "Dermatitis contact"                 ,
    "Tachycardia"                 ,
    "Flank pain"                 ,
    "Nasopharyngitis"                 ,
    "Vulvovaginal mycotic infection"                 ,
    "Hyperglycaemia"                 ,
    "Irritability"                 ,
    "Contusion"                 ,
    "Blood pressure increased"                 ,
    "Blood creatine phosphokinase increased"                 ,
    "Hidradenitis"                 ,
    "Oesophageal candidiasis"                 ,
    "Musculoskeletal pain"                 ,
    "Injection site urticaria"                 ,
    "Anxiety"                 ,
    "Intervertebral disc protrusion"                 ,
    "Influenza"                 ,
    "Stomatitis"                 ,
    "Erythrasma"                 ,
    "Headache"                 ,
    "Blood lactate dehydrogenase increased"                 ,
    "Blood urine present"                 ,
    "Blood creatine phosphokinase increased"                 ,
    " "                 ,
    "Arthralgia"                 ,
    "Cholelithiasis"                 ,
    "Lipoma"                 ,
    "Pyrexia"                 ,
    "Back pain"                 ,
    "Back pain"                 ,
    "Hidradenitis"                 ,
    "Headache"                 ,
    "Vaccination site pain"                 ,
    "Vulvovaginal mycotic infection"                 ,
    "Influenza like illness"                 ,
    "Dyshidrotic eczema"                 ,
    "Rib fracture"                 ,
    "Psoriasis"                 ,
    "Foot fracture"                 ,
    "Folliculitis"                 ,
    "Nausea"                 ,
    "Dermatitis contact"                 ,
    "Injection site reaction"                 ,
    "Dermatitis atopic"                 ,
    "Conjunctivitis"                 ,
    "Upper respiratory tract infection"                 ,
    "Dermatitis contact"),
  AESOC    = c(
    "Infections and infestations"                 ,
    "Gastrointestinal disorders"                 ,
    "General disorders and administration site conditions"                 ,
    "Metabolism and nutrition disorders"                 ,
    "Infections and infestations"                 ,
    "Injury, poisoning and procedural complications"                 ,
    "Infections and infestations"                 ,
    "Musculoskeletal and connective tissue disorders"                 ,
    "Respiratory, thoracic and mediastinal disorders"                 ,
    "Nervous system disorders"                 ,
    "General disorders and administration site conditions"                 ,
    "Gastrointestinal disorders"                 ,
    "Gastrointestinal disorders"                 ,
    "Infections and infestations"                 ,
    "Musculoskeletal and connective tissue disorders"                 ,
    "Metabolism and nutrition disorders"                 ,
    "General disorders and administration site conditions"                 ,
    "Nervous system disorders"                 ,
    "Infections and infestations"                 ,
    "Infections and infestations"                 ,
    "Investigations"                 ,
    "Gastrointestinal disorders"                 ,
    "Gastrointestinal disorders"                 ,
    "Gastrointestinal disorders"                 ,
    "Ear and labyrinth disorders"                 ,
    "Respiratory, thoracic and mediastinal disorders"                 ,
    "General disorders and administration site conditions"                 ,
    "Infections and infestations"                 ,
    "Skin and subcutaneous tissue disorders"                 ,
    "Cardiac disorders"                 ,
    "Musculoskeletal and connective tissue disorders"                 ,
    "Infections and infestations"                 ,
    "Infections and infestations"                 ,
    "Metabolism and nutrition disorders"                 ,
    "Psychiatric disorders"                 ,
    "Injury, poisoning and procedural complications"                 ,
    "Investigations"                 ,
    "Investigations"                 ,
    "Skin and subcutaneous tissue disorders"                 ,
    "Infections and infestations"                 ,
    "Musculoskeletal and connective tissue disorders"                 ,
    "General disorders and administration site conditions"                 ,
    "Psychiatric disorders"                 ,
    "Musculoskeletal and connective tissue disorders"                 ,
    "Infections and infestations"                 ,
    "Gastrointestinal disorders"                 ,
    "Infections and infestations"                 ,
    "Nervous system disorders"                 ,
    "Investigations"                 ,
    "Investigations"                 ,
    "Investigations"                 ,
    " "                 ,
    "Musculoskeletal and connective tissue disorders"                 ,
    "Hepatobiliary disorders"                 ,
    "Neoplasms benign, malignant and unspecified (incl cysts and polyps)"                 ,
    "General disorders and administration site conditions"                 ,
    "Musculoskeletal and connective tissue disorders"                 ,
    "Musculoskeletal and connective tissue disorders"                 ,
    "Skin and subcutaneous tissue disorders"                 ,
    "Nervous system disorders"                 ,
    "General disorders and administration site conditions"                 ,
    "Infections and infestations"                 ,
    "General disorders and administration site conditions"                 ,
    "Skin and subcutaneous tissue disorders"                 ,
    "Injury, poisoning and procedural complications"                 ,
    "Skin and subcutaneous tissue disorders"                 ,
    "Injury, poisoning and procedural complications"                 ,
    "Infections and infestations"                 ,
    "Gastrointestinal disorders"                 ,
    "Skin and subcutaneous tissue disorders"                 ,
    "General disorders and administration site conditions"                 ,
    "Skin and subcutaneous tissue disorders"                 ,
    "Infections and infestations"                 ,
    "Infections and infestations"                 ,
    "Skin and subcutaneous tissue disorders"),
  AEHLT    = c(
    "Ear infections"                 ,
    "Oral soft tissue signs and symptoms"                 ,
    "Pain and discomfort NEC"                 ,
    "Diabetes mellitus (incl subtypes)"                 ,
    "Upper respiratory tract infections"                 ,
    "Skin injuries NEC"                 ,
    "Candida infections"                 ,
    "Psoriatic arthropathies"                 ,
    "Nasal congestion and inflammations"                 ,
    "Tremor (excl congenital)"                 ,
    "Injection site reactions"                 ,
    "Diarrhoea (excl infective)"                 ,
    "Stomatitis and ulceration"                 ,
    "Upper respiratory tract infections"                 ,
    "Synovial disorders"                 ,
    "Potassium imbalance"                 ,
    "Implant and catheter site reactions"                 ,
    "Seizures and seizure disorders NEC"                 ,
    "Herpes viral infections"                 ,
    "Upper respiratory tract infections"                 ,
    "Liver function analyses"                 ,
    "Stomatitis and ulceration"                 ,
    "Nausea and vomiting symptoms"                 ,
    "Nausea and vomiting symptoms"                 ,
    "Hearing losses"                 ,
    "Nasal disorders NEC"                 ,
    "Febrile disorders"                 ,
    "Infections NEC"                 ,
    "Dermatitis and eczema"                 ,
    "Rate and rhythm disorders NEC"                 ,
    "Musculoskeletal and connective tissue pain and discomfort"                 ,
    "Upper respiratory tract infections"                 ,
    "Fungal infections NEC"                 ,
    "Hyperglycaemic conditions NEC"                 ,
    "Emotional and mood disturbances NEC"                 ,
    "Skin injuries NEC"                 ,
    "Vascular tests NEC (incl blood pressure)"                 ,
    "Skeletal and cardiac muscle analyses"                 ,
    "Apocrine and eccrine gland disorders"                 ,
    "Candida infections"                 ,
    "Musculoskeletal and connective tissue pain and discomfort"                 ,
    "Injection site reactions"                 ,
    "Anxiety symptoms"                 ,
    "Intervertebral disc disorders NEC"                 ,
    "Influenza viral infections"                 ,
    "Stomatitis and ulceration"                 ,
    "Corynebacteria infections"                 ,
    "Headaches NEC"                 ,
    "Tissue enzyme analyses NEC"                 ,
    "Urinalysis NEC"                 ,
    "Skeletal and cardiac muscle analyses"                 ,
    " "                 ,
    "Joint related signs and symptoms"                 ,
    "Cholecystitis and cholelithiasis"                 ,
    "Soft tissue neoplasms benign NEC"                 ,
    "Febrile disorders"                 ,
    "Musculoskeletal and connective tissue pain and discomfort"                 ,
    "Musculoskeletal and connective tissue pain and discomfort"                 ,
    "Apocrine and eccrine gland disorders"                 ,
    "Headaches NEC"                 ,
    "Vaccination site reactions"                 ,
    "Fungal infections NEC"                 ,
    "General signs and symptoms NEC"                 ,
    "Dermatitis and eczema"                 ,
    "Thoracic cage fractures and dislocations"                 ,
    "Psoriatic conditions"                 ,
    "Limb fractures and dislocations"                 ,
    "Skin structures and soft tissue infections"                 ,
    "Nausea and vomiting symptoms"                 ,
    "Dermatitis and eczema"                 ,
    "Injection site reactions"                 ,
    "Dermatitis and eczema"                 ,
    "Eye and eyelid infections"                 ,
    "Upper respiratory tract infections"                 ,
    "Dermatitis and eczema"),
  AEHLGT   = c(
    "Infections - pathogen unspecified"                 ,
    "Oral soft tissue conditions"                 ,
    "General system disorders NEC"                 ,
    "Glucose metabolism disorders (incl diabetes mellitus)"                 ,
    "Infections - pathogen unspecified"                 ,
    "Injuries NEC"                 ,
    "Fungal infectious disorders"                 ,
    "Joint disorders"                 ,
    "Upper respiratory tract disorders (excl infections)"                 ,
    "Movement disorders (incl parkinsonism)"                 ,
    "Administration site reactions"                 ,
    "Gastrointestinal motility and defaecation conditions"                 ,
    "Oral soft tissue conditions"                 ,
    "Infections - pathogen unspecified"                 ,
    "Synovial and bursal disorders"                 ,
    "Electrolyte and fluid balance conditions"                 ,
    "Administration site reactions"                 ,
    "Seizures (incl subtypes)"                 ,
    "Viral infectious disorders"                 ,
    "Infections - pathogen unspecified"                 ,
    "Hepatobiliary investigations"                 ,
    "Oral soft tissue conditions"                 ,
    "Gastrointestinal signs and symptoms"                 ,
    "Gastrointestinal signs and symptoms"                 ,
    "Hearing disorders"                 ,
    "Upper respiratory tract disorders (excl infections)"                 ,
    "Body temperature conditions"                 ,
    "Infections - pathogen unspecified"                 ,
    "Epidermal and dermal conditions"                 ,
    "Cardiac arrhythmias"                 ,
    "Musculoskeletal and connective tissue disorders NEC"                 ,
    "Infections - pathogen unspecified"                 ,
    "Fungal infectious disorders"                 ,
    "Glucose metabolism disorders (incl diabetes mellitus)"                 ,
    "Mood disorders and disturbances NEC"                 ,
    "Injuries NEC"                 ,
    "Cardiac and vascular investigations (excl enzyme tests)"                 ,
    "Enzyme investigations NEC"                 ,
    "Skin appendage conditions"                 ,
    "Fungal infectious disorders"                 ,
    "Musculoskeletal and connective tissue disorders NEC"                 ,
    "Administration site reactions"                 ,
    "Anxiety disorders and symptoms"                 ,
    "Musculoskeletal and connective tissue deformities (incl intervertebral disc disorders)"                 ,
    "Viral infectious disorders"                 ,
    "Oral soft tissue conditions"                 ,
    "Bacterial infectious disorders"                 ,
    "Headaches"                 ,
    "Enzyme investigations NEC"                 ,
    "Renal and urinary tract investigations and urinalyses"                 ,
    "Enzyme investigations NEC"                 ,
    " "                 ,
    "Joint disorders"                 ,
    "Gallbladder disorders"                 ,
    "Soft tissue neoplasms benign"                 ,
    "Body temperature conditions"                 ,
    "Musculoskeletal and connective tissue disorders NEC"                 ,
    "Musculoskeletal and connective tissue disorders NEC"                 ,
    "Skin appendage conditions"                 ,
    "Headaches"                 ,
    "Administration site reactions"                 ,
    "Fungal infectious disorders"                 ,
    "General system disorders NEC"                 ,
    "Epidermal and dermal conditions"                 ,
    "Bone and joint injuries"                 ,
    "Epidermal and dermal conditions"                 ,
    "Bone and joint injuries"                 ,
    "Infections - pathogen unspecified"                 ,
    "Gastrointestinal signs and symptoms"                 ,
    "Epidermal and dermal conditions"                 ,
    "Administration site reactions"                 ,
    "Epidermal and dermal conditions"                 ,
    "Infections - pathogen unspecified"                 ,
    "Infections - pathogen unspecified"                 ,
    "Epidermal and dermal conditions"),
  AELLT    = c(
    "Otitis"                 ,
    "Coating in mouth"                 ,
    "Non-cardiac chest pain"                 ,
    "Diabetes mellitus"                 ,
    "Upper respiratory tract infection"                 ,
    "Contusion of lower leg"                 ,
    "Oral thrush"                 ,
    "Psoriatic arthritis aggravated"                 ,
    "Nasal congestion"                 ,
    "Tremor limb"                 ,
    "Injection site reaction"                 ,
    "Diarrhoea"                 ,
    "Stomatitis"                 ,
    "Common cold"                 ,
    "Baker's cyst"                 ,
    "Hypokalemia"                 ,
    "Catheter site bruise"                 ,
    "Convulsive movements"                 ,
    "Herpes on lip"                 ,
    "Pharyngitis"                 ,
    "AST increased"                 ,
    "Mucositis oral"                 ,
    "Nausea"                 ,
    "Nausea"                 ,
    "Deafness neurosensory"                 ,
    "Epistaxis"                 ,
    "Fever"                 ,
    "Infection"                 ,
    "Contact dermatitis"                 ,
    "Tachycardia"                 ,
    "Pain flank"                 ,
    "Common cold"                 ,
    "Vaginal yeast infection"                 ,
    "Hyperglycemia"                 ,
    "Irritability"                 ,
    "Bruise"                 ,
    "Increased blood pressure"                 ,
    "CK increased"                 ,
    "Hidradenitis suppurativa"                 ,
    "Esophageal candidiasis"                 ,
    "Musculoskeletal pain"                 ,
    "Injection site urticaria"                 ,
    "Anxiety"                 ,
    "Intervertebral disc herniation"                 ,
    "Influenza"                 ,
    "Stomatitis"                 ,
    "Erythrasma"                 ,
    "Headache"                 ,
    "LDH increased"                 ,
    "Blood in urine"                 ,
    "CK increased"                 ,
    " "                 ,
    "Aching (l) knee"                 ,
    "Cholelithiasis"                 ,
    "Lipoma"                 ,
    "Fever"                 ,
    "Low back pain"                 ,
    "Low back pain"                 ,
    "Hidradenitis suppurativa"                 ,
    "Headache"                 ,
    "Vaccination site pain"                 ,
    "Vaginal yeast infection"                 ,
    "Influenza-like symptoms"                 ,
    "Dyshidrotic eczema"                 ,
    "Rib fracture"                 ,
    "Psoriasis of scalp"                 ,
    "Foot fracture"                 ,
    "Folliculitis"                 ,
    "Nausea"                 ,
    "Contact dermatitis"                 ,
    "Injection site reaction"                 ,
    "Atopic dermatitis"                 ,
    "Conjunctivitis"                 ,
    "Upper respiratory tract infection"                 ,
    "Contact dermatitis"),
  AEPTCD   = c(
    10014011                  ,
    10075366                  ,
    10062501                  ,
    10012601                  ,
    10046306                  ,
    10050584                  ,
    10030963                  ,
    10037162                  ,
    10028735                  ,
    10044565                  ,
    10022095                  ,
    10012735                  ,
    10042128                  ,
    10028810                  ,
    10042858                  ,
    10021015                  ,
    10063587                  ,
    10039906                  ,
    10067152                  ,
    10034835                  ,
    10003481                  ,
    10042128                  ,
    10028813                  ,
    10028813                  ,
    10011891                  ,
    10015090                  ,
    10037660                  ,
    10021789                  ,
    10012442                  ,
    10043071                  ,
    10016750                  ,
    10028810                  ,
    10064899                  ,
    10020635                  ,
    10022998                  ,
    10050584                  ,
    10005750                  ,
    10005470                  ,
    10020040                  ,
    10030154                  ,
    10028391                  ,
    10022107                  ,
    10002855                  ,
    10050296                  ,
    10022000                  ,
    10042128                  ,
    10015248                  ,
    10019211                  ,
    10005630                  ,
    10018870                  ,
    10005470                  ,
    NA                  ,
    10003239                  ,
    10008629                  ,
    10024612                  ,
    10037660                  ,
    10003988                  ,
    10003988                  ,
    10020040                  ,
    10019211                  ,
    10068879                  ,
    10064899                  ,
    10022004                  ,
    10013913                  ,
    10039117                  ,
    10037153                  ,
    10016970                  ,
    10016936                  ,
    10028813                  ,
    10012442                  ,
    10022095                  ,
    10012438                  ,
    10010741                  ,
    10046306                  ,
    10012442 ),
  AELLTCD  = c(
    10033071                  ,
    10075366                  ,
    10062501                  ,
    10012601                  ,
    10046306                  ,
    10010862                  ,
    10031026                  ,
    10037161                  ,
    10028735                  ,
    10044572                  ,
    10022095                  ,
    10012735                  ,
    10042128                  ,
    10010106                  ,
    10004069                  ,
    10021018                  ,
    10063587                  ,
    10010925                  ,
    10019946                  ,
    10034835                  ,
    10003544                  ,
    10028130                  ,
    10028813                  ,
    10028813                  ,
    10011891                  ,
    10015090                  ,
    10016558                  ,
    10021789                  ,
    10010790                  ,
    10043071                  ,
    10033399                  ,
    10010106                  ,
    10046946                  ,
    10020639                  ,
    10022998                  ,
    10006502                  ,
    10021655                  ,
    10009219                  ,
    10020041                  ,
    10015365                  ,
    10028391                  ,
    10022107                  ,
    10002855                  ,
    10048856                  ,
    10022000                  ,
    10042128                  ,
    10015248                  ,
    10019211                  ,
    10024051                  ,
    10005604                  ,
    10009219                  ,
    NA                  ,
    10000444                  ,
    10008629                  ,
    10024612                  ,
    10016558                  ,
    10024891                  ,
    10024891                  ,
    10020041                  ,
    10019211                  ,
    10068879                  ,
    10046946                  ,
    10022009                  ,
    10013913                  ,
    10039117                  ,
    10037157                  ,
    10016970                  ,
    10016936                  ,
    10028813                  ,
    10010790                  ,
    10022095                  ,
    10003639                  ,
    10010741                  ,
    10046306                  ,
    10010790 ),
  AEHLTCD  = c(
    10014013                  ,
    10031021                  ,
    10033372                  ,
    10012602                  ,
    10046309                  ,
    10027699                  ,
    10007134                  ,
    10037163                  ,
    10028736                  ,
    10044566                  ,
    10022097                  ,
    10012736                  ,
    10042129                  ,
    10046309                  ,
    10013360                  ,
    10036451                  ,
    10021544                  ,
    10039912                  ,
    10019972                  ,
    10046309                  ,
    10024689                  ,
    10042129                  ,
    10028817                  ,
    10028817                  ,
    10011879                  ,
    10028731                  ,
    10016286                  ,
    10021902                  ,
    10012435                  ,
    10037908                  ,
    10068757                  ,
    10046309                  ,
    10017536                  ,
    10020638                  ,
    10014556                  ,
    10027699                  ,
    10047110                  ,
    10040768                  ,
    10002982                  ,
    10007134                  ,
    10068757                  ,
    10022097                  ,
    10002869                  ,
    10022635                  ,
    10022005                  ,
    10042129                  ,
    10011210                  ,
    10019233                  ,
    10043891                  ,
    10046512                  ,
    10040768                  ,
    NA                  ,
    10023226                  ,
    10008616                  ,
    10041295                  ,
    10016286                  ,
    10068757                  ,
    10068757                  ,
    10002982                  ,
    10019233                  ,
    10068754                  ,
    10017536                  ,
    10018072                  ,
    10012435                  ,
    10043467                  ,
    10065874                  ,
    10075886                  ,
    10040786                  ,
    10028817                  ,
    10012435                  ,
    10022097                  ,
    10012435                  ,
    10015909                  ,
    10046309                  ,
    10012435 ),
  AEHLGTCD = c(
    10021879                  ,
    10031013                  ,
    10018073                  ,
    10018424                  ,
    10021879                  ,
    10022114                  ,
    10017528                  ,
    10023213                  ,
    10046304                  ,
    10028037                  ,
    10001316                  ,
    10017977                  ,
    10031013                  ,
    10021879                  ,
    10013361                  ,
    10014412                  ,
    10001316                  ,
    10039911                  ,
    10047438                  ,
    10021879                  ,
    10019809                  ,
    10031013                  ,
    10018012                  ,
    10018012                  ,
    10019243                  ,
    10046304                  ,
    10005908                  ,
    10021879                  ,
    10014982                  ,
    10007521                  ,
    10028393                  ,
    10021879                  ,
    10017528                  ,
    10018424                  ,
    10027946                  ,
    10022114                  ,
    10007512                  ,
    10014938                  ,
    10040798                  ,
    10017528                  ,
    10028393                  ,
    10001316                  ,
    10002861                  ,
    10028377                  ,
    10047438                  ,
    10031013                  ,
    10004018                  ,
    10019231                  ,
    10014938                  ,
    10038362                  ,
    10014938                  ,
    NA                  ,
    10023213                  ,
    10017628                  ,
    10041294                  ,
    10005908                  ,
    10028393                  ,
    10028393                  ,
    10040798                  ,
    10019231                  ,
    10001316                  ,
    10017528                  ,
    10018073                  ,
    10014982                  ,
    10005942                  ,
    10014982                  ,
    10005942                  ,
    10021879                  ,
    10018012                  ,
    10014982                  ,
    10001316                  ,
    10014982                  ,
    10021879                  ,
    10021879                  ,
    10014982 ),
  AESOCCD  = c(
    10021881                  ,
    10017947                  ,
    10018065                  ,
    10027433                  ,
    10021881                  ,
    10022117                  ,
    10021881                  ,
    10028395                  ,
    10038738                  ,
    10029205                  ,
    10018065                  ,
    10017947                  ,
    10017947                  ,
    10021881                  ,
    10028395                  ,
    10027433                  ,
    10018065                  ,
    10029205                  ,
    10021881                  ,
    10021881                  ,
    10022891                  ,
    10017947                  ,
    10017947                  ,
    10017947                  ,
    10013993                  ,
    10038738                  ,
    10018065                  ,
    10021881                  ,
    10040785                  ,
    10007541                  ,
    10028395                  ,
    10021881                  ,
    10021881                  ,
    10027433                  ,
    10037175                  ,
    10022117                  ,
    10022891                  ,
    10022891                  ,
    10040785                  ,
    10021881                  ,
    10028395                  ,
    10018065                  ,
    10037175                  ,
    10028395                  ,
    10021881                  ,
    10017947                  ,
    10021881                  ,
    10029205                  ,
    10022891                  ,
    10022891                  ,
    10022891                  ,
    NA                  ,
    10028395                  ,
    10019805                  ,
    10029104                  ,
    10018065                  ,
    10028395                  ,
    10028395                  ,
    10040785                  ,
    10029205                  ,
    10018065                  ,
    10021881                  ,
    10018065                  ,
    10040785                  ,
    10022117                  ,
    10040785                  ,
    10022117                  ,
    10021881                  ,
    10017947                  ,
    10040785                  ,
    10018065                  ,
    10040785                  ,
    10021881                  ,
    10021881                  ,
    10040785 ),
  AEBDSYCD = c(
    NA                  ,
    NA                  ,
    NA                  ,
    NA                  ,
    NA                  ,
    NA                  ,
    NA                  ,
    NA                  ,
    NA                  ,
    NA                  ,
    NA                  ,
    NA                  ,
    NA                  ,
    NA                  ,
    NA                  ,
    NA                  ,
    NA                  ,
    NA                  ,
    NA                  ,
    NA                  ,
    NA                  ,
    NA                  ,
    NA                  ,
    NA                  ,
    NA                  ,
    NA                  ,
    NA                  ,
    NA                  ,
    NA                  ,
    NA                  ,
    NA                  ,
    NA                  ,
    NA                  ,
    NA                  ,
    NA                  ,
    NA                  ,
    NA                  ,
    NA                  ,
    NA                  ,
    NA                  ,
    NA                  ,
    NA                  ,
    NA                  ,
    NA                  ,
    NA                  ,
    NA                  ,
    NA                  ,
    NA                  ,
    NA                  ,
    NA                  ,
    NA                  ,
    NA                  ,
    NA                  ,
    NA                  ,
    NA                  ,
    NA                  ,
    NA                  ,
    NA                  ,
    NA                  ,
    NA                  ,
    NA                  ,
    NA                  ,
    NA                  ,
    NA                  ,
    NA                  ,
    NA                  ,
    NA                  ,
    NA                  ,
    NA                  ,
    NA                  ,
    NA                  ,
    NA                  ,
    NA                  ,
    NA                  ,
    NA )
)

cm_terms <- tibble::tibble(
  CMTRT   = c(
    "MEASLES STAGE B"        , "HIB STAGE B"        , "PERTUSSIS STAGE 2"        , "RIFAMPICINUM"        , "PYRIDOSTIGMINE BROMIDE"        , "PARACETEMOL"        , "KETALAR"        , "CLEXANE"        , "ESOMEPRAZOLE MAGNESIUM"        , "DEPAKENE R"        , "TRETINOIN 0.025%"        , "BETAMETHASONE VALERATE"        , "DOXYCYCLINE"        , "CRESTOR"        , "MYCOSTATIN DROPS"        , "PERTUSSIS STAGE B"        , "HIRUDOID LOTION"        , "CEFCAPENE PIVOXIL HYDROCHLORIDE"        , "PABRON S ALPHA"        , "CELEBREX"        , "SIMVASTATIN"        , "LIZINNA"        , "TOPIRAMATE TABLETS"        , "FURAGINA"        , "OXYCODONE"        , "PARACETAMOL"        , "AMOXICILLIN HYDRATE CAPSULE"        , "VITAMIN D (CHOLECALCIFEROL)"        , "HYAKUSOGAN"        , "SARS-COV-2 VACCINATION 1ST DOSE - PFIZER"        , "DOMPERIDONE TABLETS"        , "BEROCCA"        , "YASMIN"        , "CEFTRIAXONE"        , "ZINC GLUCONATE"        , "PARACETAMOL"        , "PREDNISOLONE"        , "CHOLECALCIFEROL"        , "MONTELUKAST TABLETS"        , "TOPINA"        , "POLIO STAGE B"        , "BETASERC - BETAHISTINI DIHYDROCHLORIDUM"        , "ANTI COVID19 VACCINE (COMIRNATY)"        , "FLUCONAZOLE"        , "E KEPPRA TABLETS"        , "PARACETAMOL"        , "IBUPROFENE"        , "PARACETAMOL"        , "RIFAMPICIN"        , "CANNABIS"        , "PERTUSSIS"        , "LEMSIP"        , "BENZOYL PEROXIDE"        , "DIFLUCAN"        , "ACIDUM FOLICUM"        , "LAMOTRIGINE"        , "TETAGAM P (HUMAN ANTI-TETANUS IMMUNOGLOBULIN)"        , "LOPERAMIDE"        , "PARACETAMOL"        , "PARACETAMOL"        , "COVID 19 VACCINATION SPIKEVAX"        , "PARACETAMOL"        , "GLUCAPHAGE XR 1000"        , "SEPTRIN"        , "MENVEO"        , "LYSINE"        , "LIBEXIN"        , "ELOCOM CREAM"        , "LOXOPROFEN SODIUM HYDRATE"        , "NAPROXEN"        , "COD LIVER OIL"        , "CEFUROXIME"        , "VITAMIN C"        , "LIDOCAINE HYDROCHLORIDE"        , "HUMIRA"        , "IRFEN"        , "YASMINELLE"        , "GEMFIBROZIL"        , "LIDOCAINE CREAM"        , "AKNENORMIN"        , "MODERNA COVID-19[LOT002C21] VACCINE"        , "DOXYCYCLINE"        , "COVERSYL (PERINDOPRIL 8 MG/INDAPAMIDE 2.5 MG)"        , "SHIN LULU A GOLD DX"        , "ZINC"        , "NAPAGELN LOTION"        , "METHOTREXATE"        , "PREDNISOLONE"        , "PYRIDOSTIGMINE"        , "VITAMIN D"),
  CMDECOD = c(
    "MEASLES VACCINE"        , "HIB VACCINE"        , "PERTUSSIS VACCINE"        , "RIFAMPICIN"        , "PYRIDOSTIGMINE BROMIDE"        , "PARACETAMOL"        , "KETAMINE HYDROCHLORIDE"        , "ENOXAPARIN SODIUM"        , "ESOMEPRAZOLE MAGNESIUM"        , "VALPROATE SODIUM"        , "TRETINOIN"        , "BETAMETHASONE VALERATE"        , "DOXYCYCLINE"        , "ROSUVASTATIN CALCIUM"        , "NYSTATIN"        , "PERTUSSIS VACCINE"        , "MUCOPOLYSACCHARIDE POLYSULFURIC ACID ESTER"        , "CEFCAPENE PIVOXIL HYDROCHLORIDE"        , "OTHER COLD PREPARATIONS"        , "CELECOXIB"        , "SIMVASTATIN"        , "ETHINYLESTRADIOL;NORGESTIMATE"        , "TOPIRAMATE"        , "FURAZIDIN"        , "OXYCODONE"        , "PARACETAMOL"        , "AMOXICILLIN TRIHYDRATE"        , "COLECALCIFEROL"        , "DRUGS FOR ACID RELATED DISORDERS"        , "TOZINAMERAN"        , "DOMPERIDONE"        , "ASCORBIC ACID;BIOTIN;CALCIUM CARBONATE;MAGNESIUM;VITAMIN B NOS"        , "DROSPIRENONE;ETHINYLESTRADIOL"        , "CEFTRIAXONE"        , "ZINC GLUCONATE"        , "PARACETAMOL"        , "PREDNISOLONE"        , "COLECALCIFEROL"        , "MONTELUKAST"        , "TOPIRAMATE"        , "POLIO VACCINE"        , "BETAHISTINE HYDROCHLORIDE"        , "TOZINAMERAN"        , "FLUCONAZOLE"        , "LEVETIRACETAM"        , "PARACETAMOL"        , "IBUPROFEN"        , "PARACETAMOL"        , "RIFAMPICIN"        , "CANNABIS SATIVA"        , "PERTUSSIS VACCINE"        , "PARACETAMOL"        , "BENZOYL PEROXIDE"        , "FLUCONAZOLE"        , "FOLIC ACID"        , "LAMOTRIGINE"        , "IMMUNOGLOBULIN HUMAN ANTI-TETANUS"        , "LOPERAMIDE"        , "PARACETAMOL"        , "PARACETAMOL"        , "COVID-19 VACCINE MRNA (MRNA 1273)"        , "PARACETAMOL"        , "METFORMIN HYDROCHLORIDE"        , "SULFAMETHOXAZOLE;TRIMETHOPRIM"        , "MENINGOCOCCAL VACCINE A/C/Y/W CONJ (CRM197)"        , "LYSINE"        , "PRENOXDIAZIN HYDROCHLORIDE"        , "MOMETASONE FUROATE"        , "LOXOPROFEN SODIUM DIHYDRATE"        , "NAPROXEN"        , "COD-LIVER OIL"        , "CEFUROXIME"        , "ASCORBIC ACID"        , "LIDOCAINE HYDROCHLORIDE"        , "ADALIMUMAB"        , "IBUPROFEN"        , "DROSPIRENONE;ETHINYLESTRADIOL BETADEX CLATHRATE"        , "GEMFIBROZIL"        , "LIDOCAINE"        , "ISOTRETINOIN"        , "COVID-19 VACCINE MRNA (MRNA 1273)"        , "DOXYCYCLINE"        , "INDAPAMIDE;PERINDOPRIL"        , "ATROPA BELLADONNA TOTAL ALKALOID EX/09506901/"        , "ZINC"        , "FELBINAC"        , "METHOTREXATE"        , "PREDNISOLONE"        , "PYRIDOSTIGMINE"        , "VITAMIN D NOS"),
  CMCAT   = c(
    "VACCINATIONS"        , "VACCINATIONS"        , "VACCINATIONS"        , "GENERAL"        , "GENERAL"        , "GENERAL"        , "ANALGESICS"        , "GENERAL"        , "GENERAL"        , "GENERAL"        , "GENERAL"        , "GENERAL"        , "GENERAL"        , "GENERAL"        , "GENERAL"        , "VACCINATIONS"        , "GENERAL"        , "GENERAL"        , "GENERAL"        , "GENERAL"        , "GENERAL"        , "GENERAL"        , "GENERAL"        , "GENERAL"        , "ANALGESICS"        , "GENERAL"        , "GENERAL"        , "GENERAL"        , "GENERAL"        , "VACCINATIONS"        , "GENERAL"        , "GENERAL"        , "GENERAL"        , "GENERAL"        , "GENERAL"        , "GENERAL"        , "GENERAL"        , "GENERAL"        , "GENERAL"        , "GENERAL"        , "VACCINATIONS"        , "GENERAL"        , "GENERAL"        , "GENERAL"        , "GENERAL"        , "GENERAL"        , "ANALGESICS"        , "GENERAL"        , "GENERAL"        , "GENERAL"        , "VACCINATIONS"        , "GENERAL"        , "GENERAL"        , "GENERAL"        , "GENERAL"        , "GENERAL"        , "GENERAL"        , "GENERAL"        , "GENERAL"        , "GENERAL"        , "GENERAL"        , "GENERAL"        , "GENERAL"        , "GENERAL"        , "VACCINATIONS"        , "GENERAL"        , "GENERAL"        , "GENERAL"        , "GENERAL"        , "GENERAL"        , "GENERAL"        , "GENERAL"        , "GENERAL"        , "ANALGESICS"        , "GENERAL"        , "ANALGESICS"        , "GENERAL"        , "GENERAL"        , "GENERAL"        , "GENERAL"        , "GENERAL"        , "GENERAL"        , "GENERAL"        , "GENERAL"        , "GENERAL"        , "GENERAL"        , "GENERAL"        , "GENERAL"        , "GENERAL"        , "GENERAL"),
  CMDUR   = c(
    25         , 8         , 12         , 26         , 27         , 6         , NA         , NA         , 5         , 8         , 10         , 20         , 25         , NA         , 2         , 279         , 26         , NA         , 4         , 20         , 90         , NA         , 8         , 3         , 20         , 9         , 136         , 4         , 22         , NA         , 226         , 9         , 251         , 18         , 8         , 4         , NA         , 25         , NA         , NA         , NA         , 109         , 14         , 279         , 11         , 23         , 6         , NA         , 26         , NA         , 11         , 23         , 17         , 5         , NA         , 25         , 15         , 4         , 27         , 24         , 4         , 18         , 16         , 22         , 268         , 20         , 6         , 22         , 6         , 4         , NA         , NA         , NA         , 264         , NA         , NA         , 8         , 24         , 1         , 21         , 24         , 21         , NA         , 13         , 296         , 27         , 21         , 19         , NA         , 4 )
)


